### ISSUE TITLE
Slight Consistency of the n_t Setting Between Pseudo-Code and Source Code of Algoirthm 1

### ISSUE THREAD

**Issue by ghost** [jparkerholder/ASEBO#3]
I noticed a slight inconsitency of the ```n_t``` (which is ```n_samples``` in the source code) setting between pseudo-code and source code of Algorithm 1.
In pseuo-code of Algoithm 1 (see the NeurIPS paper), ```Take n_t = d. Sample g_1,...,g_nt from N(0, I_d) (independently).```. Obviously, ```d``` is the dimension size of the optimization problem.
However, in the source code, a more flexible option is given (the default value is 100), as presented below:
[n_samples = params['num_sensings']](https://github.com/jparkerholder/ASEBO/blob/master/asebo/es.py#L45).
For large-scale optimization (e.g., ```d > 1000```), how to better set ```n_t```, which is used before ```k``` iterations? Random search or grid search? [Of source, it will be automatically set after ```k``` iterations.]

Thanks to @jparkerholder

**Comment by jparkerholder** [comment]
Hey - apologies for the delay in getting back! 

The d used in the code is just for the initial steps before we switch to using the dimension of the active subspace. In the pseudocode you can see the if statement:

```
if t < l then:
Take nt = d.
```

It is the same here.

Cheers!
